# Generated by Django 3.0.3 on 2020-03-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_mainpagecounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpagecounter',
            name='years',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
