# Generated by Django 3.0.3 on 2020-03-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_mainpagecounter_years'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('img', models.ImageField(blank=True, upload_to='photos/')),
            ],
        ),
    ]
