# Generated by Django 3.0.3 on 2020-02-20 23:47

from django.db import migrations, models
import galleries.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('img1', models.ImageField(upload_to=galleries.models.Gallery.get_image_path)),
                ('img2', models.ImageField(upload_to=galleries.models.Gallery.get_image_path)),
                ('img3', models.ImageField(upload_to=galleries.models.Gallery.get_image_path)),
                ('img4', models.ImageField(upload_to=galleries.models.Gallery.get_image_path)),
                ('img5', models.ImageField(blank=True, upload_to=galleries.models.Gallery.get_image_path)),
                ('img6', models.ImageField(blank=True, upload_to=galleries.models.Gallery.get_image_path)),
                ('img7', models.ImageField(blank=True, upload_to=galleries.models.Gallery.get_image_path)),
                ('img8', models.ImageField(blank=True, upload_to=galleries.models.Gallery.get_image_path)),
                ('img9', models.ImageField(blank=True, upload_to=galleries.models.Gallery.get_image_path)),
                ('img10', models.ImageField(blank=True, upload_to=galleries.models.Gallery.get_image_path)),
                ('img11', models.ImageField(blank=True, upload_to=galleries.models.Gallery.get_image_path)),
                ('img12', models.ImageField(blank=True, upload_to=galleries.models.Gallery.get_image_path)),
                ('img13', models.ImageField(blank=True, upload_to=galleries.models.Gallery.get_image_path)),
                ('img14', models.ImageField(blank=True, upload_to=galleries.models.Gallery.get_image_path)),
                ('img15', models.ImageField(blank=True, upload_to=galleries.models.Gallery.get_image_path)),
                ('tags', models.ManyToManyField(to='galleries.Tag')),
            ],
        ),
    ]
