# Generated by Django 3.0.3 on 2020-02-24 13:56

from django.db import migrations, models
import galleries.models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0003_auto_20200224_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='img5',
            field=models.ImageField(upload_to=galleries.models.Gallery.get_image_path),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
