# Generated by Django 3.0.3 on 2020-02-24 18:00

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(max_length=1100)),
                ('date', models.DateField(auto_now_add=True)),
                ('img1', models.ImageField(upload_to=projects.models.Project.get_image_path)),
                ('img2', models.ImageField(upload_to=projects.models.Project.get_image_path)),
                ('img3', models.ImageField(upload_to=projects.models.Project.get_image_path)),
                ('img4', models.ImageField(upload_to=projects.models.Project.get_image_path)),
                ('img5', models.ImageField(blank=True, upload_to=projects.models.Project.get_image_path)),
                ('img6', models.ImageField(blank=True, upload_to=projects.models.Project.get_image_path)),
                ('img7', models.ImageField(blank=True, upload_to=projects.models.Project.get_image_path)),
                ('img8', models.ImageField(blank=True, upload_to=projects.models.Project.get_image_path)),
                ('img9', models.ImageField(blank=True, upload_to=projects.models.Project.get_image_path)),
                ('img10', models.ImageField(blank=True, upload_to=projects.models.Project.get_image_path)),
                ('slug', models.SlugField(default='', editable=False)),
            ],
        ),
    ]
